# Generated by Django 6.1.1 on 2026-09-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palestrantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_evento', models.DateField()),
                ('capacidade_maxima', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='palestrantes.palestrante')),
            ],
        ),
    ]
